version: '3'

services:
  backend:
    build: ./backend
    depends_on:
      - db 
  frontend:
    build: ./frontend
    ports:
      - "127.0.10.1:8080:80"
    volumes:
      - ./config/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend   
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=hub
      - MYSQL_PASSWORD=pass
      - MYSQL_DATABASE=hub


volumes:
  ide-project: